export const companies = [
  {
    name: "Microsoft",
    difficulty: "Hard",
    timeline: "May - August",
    salaryRange: {
      intern: "₹80K - ₹1.2L/month",
      fresher: "₹18 - ₹45 LPA",
    },
    careersUrl: "https://careers.microsoft.com",
    overview: "Microsoft hires for product engineering, cloud, AI, and platform roles.",
    roles: ["Software Engineer Intern", "SDE I", "Frontend Engineer", "Backend Engineer"],
    oaPattern: "2 coding questions, MCQs on CS fundamentals, and problem solving.",
    topics: ["Arrays", "Strings", "Trees", "Graphs", "Dynamic Programming"],
    resources: ["Microsoft Learn", "LeetCode Microsoft tagged questions", "System Design basics"],
    tips: ["Focus on clean code", "Practice behavioral questions", "Revise OS, DBMS, CN basics"],
    experiences: ["Community experiences can be added through future contributions."],
  },
  {
    name: "Google",
    difficulty: "Hard",
    timeline: "July - October",
    salaryRange: {
      intern: "₹1L - ₹1.5L/month",
      fresher: "₹25 - ₹60 LPA",
    },
    careersUrl: "https://careers.google.com",
    overview: "Google focuses strongly on problem solving, DSA, scalability, and fundamentals.",
    roles: ["Software Engineering Intern", "STEP Intern", "SWE I"],
    oaPattern: "Coding-heavy assessment with strong DSA focus.",
    topics: ["Graphs", "DP", "Recursion", "Trees", "Hashing"],
    resources: ["Google Careers", "LeetCode Google tagged questions", "CS fundamentals"],
    tips: ["Explain your approach clearly", "Optimize time and space complexity"],
    experiences: ["Community driven interview experiences will be expanded."],
  },
  {
    name: "Amazon",
    difficulty: "Medium-Hard",
    timeline: "June - September",
    salaryRange: {
      intern: "₹70K - ₹1.1L/month",
      fresher: "₹18 - ₹45 LPA",
    },
    careersUrl: "https://www.amazon.jobs",
    overview: "Amazon evaluates DSA, leadership principles, and practical coding skills.",
    roles: ["SDE Intern", "SDE I", "Backend Engineer"],
    oaPattern: "2 coding questions, work simulation, aptitude/behavioral round.",
    topics: ["Arrays", "Sliding Window", "Trees", "Graphs", "Heaps"],
    resources: ["Amazon Jobs", "Leadership Principles", "LeetCode Amazon questions"],
    tips: ["Prepare STAR answers", "Know Amazon leadership principles"],
    experiences: ["Community submitted experiences can be added."],
  },
  {
    name: "Adobe",
    difficulty: "Medium-Hard",
    timeline: "July - October",
    salaryRange: {
      intern: "₹60K - ₹1L/month",
      fresher: "₹15 - ₹35 LPA",
    },
    careersUrl: "https://careers.adobe.com",
    overview: "Adobe hires for product engineering, cloud, design tools, and platform teams.",
    roles: ["SDE Intern", "Software Engineer", "Frontend Engineer"],
    oaPattern: "Coding questions, aptitude, technical interview.",
    topics: ["Arrays", "Strings", "DP", "OOP", "DBMS"],
    resources: ["Adobe Careers", "LeetCode Adobe tagged questions"],
    tips: ["Revise OOP and projects well"],
    experiences: ["Community driven section."],
  },
  {
    name: "Atlassian",
    difficulty: "Hard",
    timeline: "August - November",
    salaryRange: {
      intern: "₹80K - ₹1.3L/month",
      fresher: "₹20 - ₹50 LPA",
    },
    careersUrl: "https://www.atlassian.com/company/careers",
    overview: "Atlassian focuses on collaboration tools, scalable systems, and clean engineering.",
    roles: ["SDE Intern", "Frontend Engineer", "Backend Engineer"],
    oaPattern: "Coding round, system/design discussion, behavioral round.",
    topics: ["Graphs", "DP", "System Design", "JavaScript", "APIs"],
    resources: ["Atlassian Careers", "Frontend and backend interview guides"],
    tips: ["Prepare projects deeply", "Practice design thinking"],
    experiences: ["Community driven section."],
  },
  {
    name: "Zoho",
    difficulty: "Medium",
    timeline: "Year-round",
    salaryRange: {
      intern: "₹20K - ₹50K/month",
      fresher: "₹5 - ₹12 LPA",
    },
    careersUrl: "https://www.zoho.com/careers",
    overview: "Zoho focuses on programming fundamentals, logic building, and practical problem solving.",
    roles: ["Software Developer", "Product Developer", "Intern"],
    oaPattern: "Aptitude, basic programming, advanced coding, face-to-face technical rounds.",
    topics: ["Patterns", "Arrays", "Strings", "Recursion", "OOP"],
    resources: ["Zoho interview preparation sheets", "Basic DSA practice"],
    tips: ["Practice dry runs", "Focus on logic more than shortcuts"],
    experiences: ["Community driven section."],
  },
  {
    name: "Freshworks",
    difficulty: "Medium",
    timeline: "June - September",
    salaryRange: {
      intern: "₹40K - ₹80K/month",
      fresher: "₹8 - ₹18 LPA",
    },
    careersUrl: "https://www.freshworks.com/company/careers",
    overview: "Freshworks hires for SaaS product development and full-stack engineering roles.",
    roles: ["SDE Intern", "Frontend Engineer", "Backend Engineer"],
    oaPattern: "Coding, aptitude, technical interview, project discussion.",
    topics: ["Arrays", "Strings", "Web Development", "DBMS", "APIs"],
    resources: ["Freshworks Careers", "Full-stack project guides"],
    tips: ["Show strong product thinking", "Prepare web projects clearly"],
    experiences: ["Community driven section."],
  },
  {
    name: "TCS",
    difficulty: "Easy-Medium",
    timeline: "August - December",
    salaryRange: {
      intern: "₹10K - ₹25K/month",
      fresher: "₹3.5 - ₹9 LPA",
    },
    careersUrl: "https://www.tcs.com/careers",
    overview: "TCS hires through NQT and campus drives for multiple IT roles.",
    roles: ["Ninja", "Digital", "Prime", "Software Engineer"],
    oaPattern: "Aptitude, verbal, reasoning, coding.",
    topics: ["Basic Coding", "Arrays", "Strings", "SQL", "OOP"],
    resources: ["TCS NQT practice", "Aptitude preparation"],
    tips: ["Practice speed and accuracy", "Revise basics well"],
    experiences: ["Community driven section."],
  },
  {
    name: "Infosys",
    difficulty: "Easy-Medium",
    timeline: "August - December",
    salaryRange: {
      intern: "₹10K - ₹25K/month",
      fresher: "₹3.6 - ₹9.5 LPA",
    },
    careersUrl: "https://www.infosys.com/careers",
    overview: "Infosys hires through campus drives and certification based programs.",
    roles: ["System Engineer", "Power Programmer", "Specialist Programmer"],
    oaPattern: "Aptitude, pseudocode, coding questions.",
    topics: ["Pseudocode", "Arrays", "Strings", "DBMS", "OOP"],
    resources: ["Infosys recruitment practice", "Programming fundamentals"],
    tips: ["Focus on pseudocode and aptitude"],
    experiences: ["Community driven section."],
  },
  {
    name: "Accenture",
    difficulty: "Easy-Medium",
    timeline: "Year-round",
    salaryRange: {
      intern: "₹15K - ₹30K/month",
      fresher: "₹4.5 - ₹8 LPA",
    },
    careersUrl: "https://www.accenture.com/in-en/careers",
    overview: "Accenture hires for software, consulting, cloud, and analyst roles.",
    roles: ["ASE", "Intern", "Software Engineer"],
    oaPattern: "Cognitive ability, technical MCQs, coding, communication.",
    topics: ["Aptitude", "Basic Coding", "SQL", "OOP"],
    resources: ["Accenture placement preparation", "Communication practice"],
    tips: ["Prepare communication round well"],
    experiences: ["Community driven section."],
  },
  {
    name: "Wipro",
    difficulty: "Easy-Medium",
    timeline: "August - December",
    salaryRange: {
      intern: "₹10K - ₹25K/month",
      fresher: "₹3.5 - ₹8 LPA",
    },
    careersUrl: "https://careers.wipro.com",
    overview: "Wipro hires through campus and national talent programs.",
    roles: ["Project Engineer", "Software Developer", "Intern"],
    oaPattern: "Aptitude, essay writing, coding, HR.",
    topics: ["Aptitude", "Arrays", "Strings", "OOP", "SQL"],
    resources: ["Wipro placement papers", "Basic DSA"],
    tips: ["Practice essay and communication"],
    experiences: ["Community driven section."],
  },
  {
    name: "Capgemini",
    difficulty: "Easy-Medium",
    timeline: "August - December",
    salaryRange: {
      intern: "₹10K - ₹25K/month",
      fresher: "₹3.8 - ₹8 LPA",
    },
    careersUrl: "https://www.capgemini.com/careers",
    overview: "Capgemini hires for software engineering, analyst, and consulting roles.",
    roles: ["Analyst", "Software Engineer", "Intern"],
    oaPattern: "Aptitude, logical reasoning, coding, communication.",
    topics: ["Aptitude", "Basic Coding", "SQL", "OOP"],
    resources: ["Capgemini placement practice", "Coding basics"],
    tips: ["Maintain accuracy in aptitude"],
    experiences: ["Community driven section."],
  },
  {
    name: "Qualcomm",
    difficulty: "Hard",
    timeline: "July - October",
    salaryRange: {
      intern: "₹60K - ₹1L/month",
      fresher: "₹15 - ₹35 LPA",
    },
    careersUrl: "https://www.qualcomm.com/company/careers",
    overview: "Qualcomm focuses on systems, embedded, hardware-software, and performance engineering.",
    roles: ["Software Intern", "Embedded Engineer", "Systems Engineer"],
    oaPattern: "Coding, OS, CN, C/C++, electronics fundamentals depending on role.",
    topics: ["C++", "OS", "CN", "Bit Manipulation", "DSA"],
    resources: ["Qualcomm Careers", "OS and C++ preparation"],
    tips: ["Revise low-level concepts strongly"],
    experiences: ["Community driven section."],
  },
  {
    name: "Oracle",
    difficulty: "Medium-Hard",
    timeline: "July - October",
    salaryRange: {
      intern: "₹50K - ₹90K/month",
      fresher: "₹12 - ₹30 LPA",
    },
    careersUrl: "https://www.oracle.com/careers",
    overview: "Oracle hires for database, cloud, backend, and enterprise software teams.",
    roles: ["SDE Intern", "Application Developer", "Backend Engineer"],
    oaPattern: "Coding, SQL, DBMS, technical interview.",
    topics: ["SQL", "DBMS", "Arrays", "Trees", "OOP"],
    resources: ["Oracle Careers", "SQL and DBMS notes"],
    tips: ["Prepare DBMS very well"],
    experiences: ["Community driven section."],
  },
  {
    name: "Salesforce",
    difficulty: "Medium-Hard",
    timeline: "July - October",
    salaryRange: {
      intern: "₹60K - ₹1L/month",
      fresher: "₹14 - ₹35 LPA",
    },
    careersUrl: "https://careers.salesforce.com",
    overview: "Salesforce hires for cloud, CRM, backend, frontend, and platform engineering.",
    roles: ["SDE Intern", "Associate Software Engineer", "Frontend Engineer"],
    oaPattern: "Coding assessment, technical interview, behavioral round.",
    topics: ["Arrays", "Strings", "DP", "Web Development", "OOP"],
    resources: ["Salesforce Careers", "Trailhead", "LeetCode Salesforce questions"],
    tips: ["Prepare projects and cloud basics"],
    experiences: ["Community driven section."],
  },
];